
// ----------------------------------------------------------------------------------------------------------------------
// DADOS DA API
export const APIdata = [
  {
    id: 1,
    date: '15/12/22',
    min_c: '24,0°C',
    max_c: '31,0°C',
    hour_hot: '0h',
    hour_could: '0h',
    icon_morning: 'Icon',
    icon_afternoon: 'Icon',
    icon_night: 'Icon',
    precipitacao: '15.0 mm',
    probabilidade: '42%',
    intensidade: '42 km/h',
    direcao: 'NNE',
    min: '42%',
    max: '42%',
    distancia: '18.1 km',
    hPa: '1042'
  },
  {
    id: 2,
    date: '15/12/22',
    min_c: '24,0°C',
    max_c: '31,0°C',
    hour_hot: '0h',
    hour_could: '0h',
    icon_morning: 'Icon',
    icon_afternoon: 'Icon',
    icon_night: 'Icon',
    precipitacao: '15.0 mm',
    probabilidade: '42%',
    intensidade: '42 km/h',
    direcao: 'NNE',
    min: '42%',
    max: '42%',
    distancia: '18.1 km',
    hPa: '1042'
  },
  {
    id: 3,
    date: '15/12/22',
    min_c: '24,0°C',
    max_c: '31,0°C',
    hour_hot: '0h',
    hour_could: '0h',
    icon_morning: 'Icon',
    icon_afternoon: 'Icon',
    icon_night: 'Icon',
    precipitacao: '15.0 mm',
    probabilidade: '42%',
    intensidade: '42 km/h',
    direcao: 'NNE',
    min: '42%',
    max: '42%',
    distancia: '18.1 km',
    hPa: '1042'
  },
  {
    id: 4,
    date: '15/12/22',
    min_c: '24,0°C',
    max_c: '31,0°C',
    hour_hot: '0h',
    hour_could: '0h',
    icon_morning: 'Icon',
    icon_afternoon: 'Icon',
    icon_night: 'Icon',
    precipitacao: '15.0 mm',
    probabilidade: '42%',
    intensidade: '42 km/h',
    direcao: 'NNE',
    min: '42%',
    max: '42%',
    distancia: '18.1 km',
    hPa: '1042'
  },
  {
    id: 5,
    date: '15/12/22',
    min_c: '24,0°C',
    max_c: '31,0°C',
    hour_hot: '0h',
    hour_could: '0h',
    icon_morning: 'Icon',
    icon_afternoon: 'Icon',
    icon_night: 'Icon',
    precipitacao: '15.0 mm',
    probabilidade: '42%',
    intensidade: '42 km/h',
    direcao: 'NNE',
    min: '42%',
    max: '42%',
    distancia: '18.1 km',
    hPa: '1042'
  },
];




